version: "3"
services:
  app:
    image: quarkus/money-transfer-service-native:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: money_transfer
    ports:
      - 5432:5433