version: "3"
services:
  app:
    image: quarkus-jar
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: money_transfer
    ports:
      - 5432:5433